[project]
name = "face-recognition-attendance-backend"
version = "0.1.0"
description = "Backend for the Face Recognition Attendance System."
requires-python = "==3.9.*"
dependencies = [
    "fastapi>=0.100.0,<0.112.0",
    "uvicorn[standard]>=0.20.0,<0.30.0"
]
